const catedata = {
	"banners": [{
		"id": 1470,
		"title": "新海诚动漫的梦幻联动",
		"cover": "https://oss-xpc6.xpccdn.com/default/wR5Z5JBrBJKWfsJGxSLpcp8Cpm47AGyxaxS5o3Jv.png",
		"url": "newstudios://app.xinpianchang.com/article/12154018?utm_source=xpcApp&utm_medium=discoveryBanner&index=1"
	}, {
		"id": 1469,
		"title": "每个镜头都能作为模板",
		"cover": "https://oss-xpc6.xpccdn.com/default/Wg3uybjJ12goVevRnbg9yADhbGdBBwe14T3ixTBX.png",
		"url": "newstudios://app.xinpianchang.com/article/12213190?utm_source=xpcApp&utm_medium=discoveryBanner&index=2"
	}, {
		"id": 1468,
		"title": "真人版的音游游戏～",
		"cover": "https://oss-xpc6.xpccdn.com/default/EsOdkMvJWvKgJcprxdeGqVJWd8ARTQ2UqF7UmaxU.png",
		"url": "newstudios://app.xinpianchang.com/article/12189885?utm_source=xpcApp&utm_medium=discoveryBanner&index=3"
	}, {
		"id": 1467,
		"title": "超强视觉冲击《享受威士忌色彩魅力》",
		"cover": "https://oss-xpc6.xpccdn.com/default/eY2E4HhlEioqGtwnDCYVnLEPI2UfWeibZmCPXaSa.png",
		"url": "newstudios://app.xinpianchang.com/article/12208803?utm_source=xpcApp&utm_medium=discoveryBanner&index=4"
	}, {
		"id": 1437,
		"title": "智云免费送百瓦棒灯",
		"cover": "https://oss-xpc6.xpccdn.com/default/Uho2Kr4y7oHrioebDRwTeiXsV1bqIOS3hC8JZypR.jpg",
		"url": "newstudios://app.xinpianchang.com/web?url=https%3A%2F%2Fwww.xinpianchang.com%2Factivity%2Fzhiyun_bd_2022%3Futm_source%3DxpcApp%26utm_medium%3DdiscoveryBanner%26index%3D5%26from%3DxpcAppDiscoveryBanner"
	}, {
		"id": 1465,
		"title": "台湾省电力公司《为生活赋能》",
		"cover": "https://oss-xpc6.xpccdn.com/default/V06McYFMs16kfPszuwHFJhzHQZsAtKr75EfEGuxB.png",
		"url": "newstudios://app.xinpianchang.com/article/11474032?utm_source=xpcApp&utm_medium=discoveryBanner&index=6"
	}],
	"recommended_position": [{
		"title": "创作人",
		"url": "newstudios://app.xinpianchang.com/creators?role_type=person&order=hot",
		"web_url": "https://www.xinpianchang.com/user/stars?userType=1",
		"icon": "https://oss-xpc0.xpccdn.com/Upload/edu/2019/01/145c3c382f1a82d.png"
	}, {
		"title": "机构",
		"url": "newstudios://app.xinpianchang.com/creators?role_type=company&order=hot",
		"web_url": "https://www.xinpianchang.com/user/stars?userType=2",
		"icon": "https://oss-xpc0.xpccdn.com/Upload/edu/2019/01/145c3c3871bd708.png"
	}, {
		"title": "正版素材",
		"url": "newstudios://app.xinpianchang.com/web?url=https%3A%2F%2Fresource.xinpianchang.com%3Forigin%3Dappdiscovery",
		"web_url": "https://resource.xinpianchang.com?origin=appdiscovery",
		"icon": "https://oss-xpc0.xpccdn.com/Upload/edu/2019/02/015c53c03cb6605.png"
	}, {
		"title": "活动",
		"url": "newstudios://app.xinpianchang.com/web?url=https%3A%2F%2Fwww.xinpianchang.com%2Factivity%3Ffrom%3Dappdiscovery",
		"web_url": "https://www.xinpianchang.com/activity?from=appdiscovery",
		"icon": "https://oss-xpc0.xpccdn.com/Upload/edu/2019/08/055d47e2511d1d8.png"
	}],
	"categories": [{
		"id": 1,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=1",
		"web_url": "https://www.xinpianchang.com/channel/index/id-1",
		"category_name": "广告",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/1.png"
	}, {
		"id": 31,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=31",
		"web_url": "https://www.xinpianchang.com/channel/index/id-31",
		"category_name": "剧情短片",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/31.png"
	}, {
		"id": 16,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=16",
		"web_url": "https://www.xinpianchang.com/channel/index/id-16",
		"category_name": "宣传片",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/16.png"
	}, {
		"id": 76,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=76",
		"web_url": "https://www.xinpianchang.com/channel/index/id-76",
		"category_name": "创意",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/76.png"
	}, {
		"id": 61,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=61",
		"web_url": "https://www.xinpianchang.com/channel/index/id-61",
		"category_name": "特殊摄影",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/61.png"
	}, {
		"id": 141,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=141",
		"web_url": "https://www.xinpianchang.com/channel/index/id-141",
		"category_name": "旅拍",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/141.png"
	}, {
		"id": 81,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=81",
		"web_url": "https://www.xinpianchang.com/channel/index/id-81",
		"category_name": "影视",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/81.png"
	}, {
		"id": 142,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=142",
		"web_url": "https://www.xinpianchang.com/channel/index/id-142",
		"category_name": "混剪",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/142.jpg"
	}, {
		"id": 143,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=143",
		"web_url": "https://www.xinpianchang.com/channel/index/id-143",
		"category_name": "器材",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/143.png"
	}, {
		"id": 144,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=144",
		"web_url": "https://www.xinpianchang.com/channel/index/id-144",
		"category_name": "干货教程",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/144.png"
	}, {
		"id": 129,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=129",
		"web_url": "https://www.xinpianchang.com/channel/index/id-129",
		"category_name": "Vlog",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2019/02/21/129.jpg"
	}, {
		"id": 145,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=145",
		"web_url": "https://www.xinpianchang.com/channel/index/id-145",
		"category_name": "古风",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/145.png"
	}, {
		"id": 29,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=29",
		"web_url": "https://www.xinpianchang.com/channel/index/id-29",
		"category_name": "短视频",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/29.png"
	}, {
		"id": 49,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=49",
		"web_url": "https://www.xinpianchang.com/channel/index/id-49",
		"category_name": "纪录",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/49.png"
	}, {
		"id": 69,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=69",
		"web_url": "https://www.xinpianchang.com/channel/index/id-69",
		"category_name": "动画",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/69.png"
	}, {
		"id": 27,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=27",
		"web_url": "https://www.xinpianchang.com/channel/index/id-27",
		"category_name": "音乐",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2018/07/18/27.png"
	}, {
		"id": 146,
		"url": "newstudios://app.xinpianchang.com/articles?category_id=146",
		"web_url": "https://www.xinpianchang.com/channel/index/id-146",
		"category_name": "极限",
		"cover": "https://oss-xpc0.xpccdn.com/uploadfile/channel/2021/04/19/146.png"
	}]
}
export default catedata
